#----------------------------------------------------------------------------
#BOP
#
# !MODULE: .bash_aliases
#
# !DESCRIPTION: A .bashrc-style file that you can use to contain your own
#  personal settings for Linux desktops.  Functions are contained in the
#  ~/.bash_functions startup file.
#\\
#\\
# !CALLING SEQUENCE:
#  . ~/.bash_aliases
#  (will also be called each time you source ~/.bashrc)
#
# !AUTHOR
#  Bob Yantosca (yantosca@seas.harvard.edu), 20 Dec 2018
#
# !REVISION HISTORY:
#  Use the gitk browser to view the revision history!
#EOP
#----------------------------------------------------------------------------
#BOC

#============================================================================
# Look-and-feel
#============================================================================

# Settings for colorization
export GREP_COLOR=32

# Override the system prompt (93 = yellow)
PS1="\[\e[1;93m\][\h \W]$\[\e[0m\] "

# Colors for directory listing
# See: http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors
export LS_COLORS='no=00:fi=00:di=01;33:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;37:*.tgz=01;37:*.arj=01;37:*.taz=01;37:*.lzh=01;37:*.zip=01;37:*.z=01;37:*.Z=01;37:*.gz=01;37:*.bz2=01;37:*.deb=01;37:*.rpm=01;37:*.jar=01;37:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.flac=01;35:*.mp3=01;35:*.mpc=01;35:*.ogg=01;35:*.wav=01;35:'

#============================================================================
# Max out certain limits
#============================================================================
ulimit -c unlimited                          # Max out core dump size
ulimit -v unlimited                          # Max out virtual memory
{%@@ if profile == "calculon" @@%}
ulimit -s 65532                              # MacOS has limited stack memory
{%@@ else @@%}
ulimit -s unlimited                          # Max out stack memory
{%@@ endif @@%}
{%@@ if profile != "cygwin" @@%}
ulimit -m unlimited                          # Max out memory
{%@@ endif @@%}

#============================================================================
# Define aliases and functions for common commands
#============================================================================

# System name
SYSTEM=$(uname -s)

# Define aliases that differ between MacOS (aka Darwin) and GNU Linux
{%@@ if profile == "bender" @@%}
alias emacs="emacs 2>/dev/null"
alias rm="rm -Iv"
alias ls="ls -CF --time-style=long-iso --color=auto"
alias supg="sudo apt update && sudo apt upgrade -y"   # Ubuntu Linux
{%@@ elif profile == "calculon" @@%}
alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
alias rm="rm -v"
alias ls="ls -CF"
{%@@ elif profile == "calculon" @@%}
alias emacs="emacs 2>/dev/null"
alias rm="rm -v"
alias ls="ls -CF"
{%@@ elif profile == "hypnotoad" @@%}
alias emacs="emacs 2>/dev/null"
alias rm="rm -Iv"
alias ls="ls -CF --time-style=long-iso --color=auto"
{%@@ endif @@%}

# Define aliases that are the same for both MacOS and Linux
alias disk="du -h -s -c"
alias g="grep -in --color=auto"
alias gt="grep -in --text"
alias m="less -CR"
alias me="xterm 2>/dev/null &"
alias proc="ps -ef | grep $USER | sort"
alias pu="rm *~"
alias pua="rm .*~"
alias sb=". ~/.bashrc"
alias sba=". ~/.bash_aliases"
alias tf="tail --follow"
alias zap="kill -9"
alias cd="cd -P"
alias c="clear"
alias h="history"
alias diff="colordiff"
alias rmcore="rm core.*"
alias cp="cp -v"
alias mv="mv -v"
alias ssh="ssh -YA"

# Directory listing commands
alias l1="ls -1"
alias ll="ls -l"
alias llt="ls -lt"
alias lltm="ls -lt | less"
alias la="ls -a"
alias lla="ls -la"
alias llh="ls -lh"

# Tmux aliases
alias tmuxnew="tmux new -s "
alias tmuxat="tmux a -t "
alias tmuxde="tmux detach "

# Slack aliases
alias slack="slack 2>/dev/null 1>/dev/null"

{%@@ if profile == "hypnotoad" @@%}
# For KPP C-I tests in the Docker container
alias dbkpp="docker build -f ./.ci-pipelines/Dockerfile -t kpp-build ."
alias drkpp="docker run -it --entrypoint /bin/bash kpp-build"
{%@@ elif profile == "calculon" @@%}
# Path o flex library for KPP (installed via Homebrew)
export KPP_FLEX_LIB_DIR=/usr/local/Cellar/flex/2.6.4_2/lib
{%@@ endif @@%}

# KPP directory change aliases
alias kh="cd ${KPP_HOME}"
alias kcp="cd ${KPP_HOME}/.ci-pipelines"
alias kct="cd ${KPP_HOME}/ci-tests"
alias kdo="cd ${KPP_HOME}/docs"
alias kdr="cd ${KPP_HOME}/drv"
alias kge="cd ${KPP_HOME}/general"
alias kmo="cd ${KPP_HOME}/models"
alias ksr="cd ${KPP_HOME}/src"
alias kut="cd ${KPP_HOME}/util"
alias kit="${KPP_HOME}/.ci-pipelines/ci-testing-script.sh"
alias kic="${KPP_HOME}/.ci-pipelines/ci-cleanup-script.sh"

# Alias for sphinx-readthedocs
alias sph="sphinx-autobuild source build/html"

#============================================================================
# Define aliases and functions for Git commands
#============================================================================
alias gui="git gui 2>/dev/null &"
alias gk="gitk 2>/dev/null &"
alias gka="gitk --all 2>/dev/null &"
alias gpo="git pull origin"
alias gl="git log"
alias glo="git log --oneline"
alias glp="git log --pretty=format:'%h : %s' --topo-order --graph"
alias update_tags="git tag -l | xargs git tag -d && git fetch -t"

# Git aliases for GEOS-Chem
#source /etc/bash_completion.d/git
alias clone_gcc="git clone --recurse-submodules git@github.com:geoschem/GCClassic.git"
alias clone_gchp="git clone --recurse-submodules git@github.com:geoschem/gchp.git"
alias clone_hco="git clone --recurse-submodules git@github.com:geoschem:hemco.git"
alias gitc="git -C CodeDir"
alias glog="git -C src/GEOS-Chem log --oneline"
alias gsu="git submodule update --init --recursive"
alias hlog="git -C src/HEMCO log --oneline"
alias hplog="git -C src/GCHP_GridComp/HEMCO_GridComp/HEMCO log --oneline"

{%@@ if profile == "calculon" @@%}
#============================================================================
# Compiler settings (MacOS)
#
# NOTE: MacOSX installs Clang as /usr/bin/gcc, so we have to manually
# force reference to gcc-11, g++-11, and gfortran-11, which HomeBrew
# installs to /usr/local/bin.  (bmy, 10/28/21)
#============================================================================
alias gcc=gcc-11
alias g++=g++-11
alias gfortran=gfortran-11
export CC=gcc
export CXX=g++-11
export FC=gfortran-11
export F77=gfortran-11
{%@@ elif profile == "hypnotoad" @@%}
#============================================================================
# Compiler settings (Linux)
#============================================================================
export CC=gcc
export CXX=g++
export FC=gfortran
export F77=gfortran

#============================================================================
# Python settings
#============================================================================
if [[ "x${PYTHONPATH}" != "x" ]]; then

    # Select Bob Y's custom environment (matplotlib 3)
    alias sab="conda activate gcpy"
    alias sdb="conda deactivate"

    # Add Python repos to $PYTHONPATH
    export PYTHONPATH=${PYTHONPATH}:${HOME}/python/gcpy

    # Ignore warnings about deprecated options
    export PYTHONWARNINGS=ignore::DeprecationWarning

    # Settings for Python packages
    export PYLINTRC=~/.pylint.rc

    # Temporary Python folder (avoids warning messages)
    export XDG_RUNTIME_DIR=/tmp/runtime-${USER}
fi

##============================================================================
## Ruby & Jekyll settings
##
## Manjaro : https://wiki.archlinux.org/index.php/Ruby
## Ubuntu  : https://jekyllrb.com/docs/installation/ubuntu/
##============================================================================

# Jekyll command
alias jserve="bundle exec jekyll serve"
{%@@ elif profile == "bender" @@%}
#============================================================================
# Compiler settings (Linux)
#============================================================================
export CC=gcc
export CXX=g++
export FC=gfortran
export F77=gfortran
{%@@ endif @@%}

#============================================================================
# Personal settings: Harvard logins
#============================================================================

# Log directly into holyjacob01
alias hj1="ssh holyjacob01"

# Log into AS
alias bmygo="ssh bmy@bmy.as.harvard.edu"

# Log into FASRC round-robin login nodes
alias rcgo="ssh ryantosca@login.rc.fas.harvard.edu"

#============================================================================
# Personal settings: AWS cloud
#============================================================================

# Amazon S3 commands
alias s3cp="aws s3 cp -request-payer=requester "
alias s3ls="aws s3 ls -request-payer=requester "

#============================================================================
# Personal settings: Dotdrop (AUR package) for managing system files
#============================================================================
alias dotdrop="~/repos/dotfiles/dotdrop.sh --cfg=~/repos/dotfiles/config.yaml"
#EOC
