name: dotdrop_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - Jinja2
  - docopt
  - ruamel.yaml
  - python-magic
  - packaging
  - pip
  - requests
  - toml
  - distro
  - tomli
  - pip:
    - tomli_W
